### ISSUE TITLE
504: GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by eddyvinsensius** [erwindosianipar/beeble#1]
can not access , pleasefix this error , thanks

![aaa](https://github.com/user-attachments/assets/7ece80f5-4b0f-43f1-983b-43b84ebd1f8e)

**Comment by erwindosianipar** [comment]
Hi @eddyvinsensius sorry for the late reply.

It's look like related to timeout request from the source or probably the network issue related
I just checked https://beeble.vercel.app/api/v1/passage/Kej/2?ver=av and no issue persist

Is the issue still happen?

**Comment by eddyvinsensius** [comment]
please check , what does this error mean?

https://beeble.vercel.app/api/v1/passage/Kej/2?ver=av, result:
{
  "url": "/api/v1/passage/Kej/2?ver=av",
  "statusCode": 500,
  "statusMessage": "Internal Server Error",
  "message": " (500 Internal Server Error (https://alkitab.sabda.org/api/passage.php?passage=Kej+2&ver=av))",
  "stack": ""
}
